/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BFST22Group10;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void Tautology() {
        assertTrue(true);
    }
}
