/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BFST22Group10;

import javafx.application.Application;
import javafx.stage.Stage;

import javax.xml.stream.XMLStreamException;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class App extends Application {
    public static void launch(String[] args) {
        Application.launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws IOException, XMLStreamException {
        String prefix = "src/main/resources";
        String file = "/Bornholm.osm";
        InputStream stream = this.getClass().getResourceAsStream(file);
        new Controller(primaryStage, stream, prefix+file);
    }

    public static void restart(Stage primaryStage, String path) throws IOException, XMLStreamException {
        File file = new File(path);
        InputStream stream = new FileInputStream(file);
        new Controller(primaryStage, stream, path);
    }
}