/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Semester1: [{type: 'autogenerated', dirName: 'SEM_01'}],
  Semester2: [{type: 'autogenerated', dirName: 'SEM_02'}],
  Semester3: [{type: 'autogenerated', dirName: 'SEM_03'}],
  Semester4: [{type: 'autogenerated', dirName: 'SEM_04'}],
  Semester5: [{type: 'autogenerated', dirName: 'SEM_05'}],
  Semester6: [{type: 'autogenerated', dirName: 'SEM_06'}],
};

module.exports = sidebars;
